### ISSUE TITLE
Dev Request

### ISSUE THREAD

**Issue by txt3rob** [yasinS/sandcastle#4]
can you also add a way for it do bucketname-company as well so it's the opposite way around? i think some do this so it might help :)

**Comment by yasinS** [comment]
Hi @txt3rob, thanks for raising an issue and for your support :) 

Apologies for the inconvenience, but upon consideration I've decided to cease development of Sandcastle. @tomdev's [Bucketeers](https://github.com/tomdev/teh_s3_bucketeers/) project incorporates a much wider range of scanning prefixes and should meet your needs here.

Thanks again!
