### ISSUE TITLE
AWSHTTPSConnection Error

### ISSUE THREAD

**Issue by arbazkiraak** [yasinS/sandcastle#5]
python sandcastle.py -t hackerone

Hello While running this tool : I m getting following output 

[+] Checking potential match: hackerone-attachments --> 403

'AWSHTTPSConnection' object has no attribute 'ssl_context'
[+] Checking potential match: hackerone --> 403

'AWSHTTPSConnection' object has no attribute 'ssl_context'
[+] Checking potential match: hackerone --> 403

'AWSHTTPSConnection' object has no attribute 'ssl_context'
[*] Enumeration of 'hackerone' buckets complete.

**Comment by yasinS** [comment]
Hi @arbazkiraak,

Thanks for getting in touch. This tool is now [deprecated](https://github.com/yasinS/sandcastle#development-ceased-sandcastle-is-at-eol), but happy to investigate the issue you're experiencing. To help diagnose the problem, please could you provide the following information?

* Operating system and version
* Current Python version (please run `python -V`)

The `SSLContext` class will be unavailable if you're running a version prior to Python 2.7.9, which may be the cause of the errors mentioned above.

**Comment by arbazkiraak** [comment]
Hey Yasin,

Thanks for the quick response . I Highly Appreciate your Response.

I'm Running Kali 2.0 and i have awscli configured.

Python Version : Python 2.7.13

I Guess the problem is with my AWS. I will try reinstalling the CLI . let me know if you have help or suggest . Thanks
 
$ aws s3 ls s3://hackerone.com

'AWSHTTPSConnection' object has no attribute 'ssl_context'
